### ISSUE TITLE
[sapl-lang] change in API of ClockPolicyInformationPoint is breaking examples with streaming policies

### ISSUE THREAD

**Issue by nniikkoollaaii** [heutelbeck/sapl-policy-engine#20]
Hey @heutelbeck , 

with this commit [here ](https://github.com/heutelbeck/sapl-policy-engine/commit/e8e992c80fb3c4473ab3008390d0ea5be7f8bf39#diff-0ab315e52b62f5386076538aeb460262ecd31ff990f405d5f2e62644916fe09bR61) you introduced a breaking change to the ClockPolicyInformationPoint API.

Now Policies using this PIP
```
...
where
  var interval = 2;
  time.localSecond(interval.<clock.ticker>) > 4;
```
for example [here](https://github.com/heutelbeck/sapl-policy-engine/blob/master/sapl-test/src/main/resources/policies/policyStreaming.sapl) are throwing a exception at runtime 
`java.util.NoSuchElementException: Value is an error: wrong number of arguments`

Can you provide a example of how to use the new ClockPIP?

After that we can enable the fixed streaming test [here](https://github.com/heutelbeck/sapl-policy-engine/blob/master/sapl-test/src/test/java/io/sapl/test/unit/usecase/E_PolicyStreamingTest.java#L59) again.

**Comment by heutelbeck** [comment]
The interval parameter moved from left-hand input to right-hand parameters.

intervall.<clock.ticker> to <clock.ticker(interval)>

Will update the reactive demo application accordingly.

Please adjust the demo tests. Thanks.
