### ISSUE TITLE
test_streamingPolicyWithVirtualTime fails with mvn install

### ISSUE THREAD

**Issue by Nipahu** [heutelbeck/sapl-policy-engine#22]
@heutelbeck @nniikkoollaaii 

When I try to install the sapl-policy-engine via `mvn clean install` the test case `test_streamingPolicyWithVirtualTime` always fails. I already stashed all my changes and tried it with latest commit on the main branch but I have the same problem.

This is the log produced by the failed test:
```
-------------------------------------------------------------------------------
Test set: io.sapl.test.unit.usecase.X_InstableTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 9.015 s <<< FAILURE! - in io.sapl.test.unit.usecase.X_InstableTest
test_streamingPolicyWithVirtualTime  Time elapsed: 9.014 s  <<< FAILURE!
java.lang.AssertionError: VerifySubscriber timed out on reactor.core.publisher.FluxPeek$PeekSubscriber@fe42a09
	at io.sapl.test.unit.usecase.X_InstableTest.test_streamingPolicyWithVirtualTime(X_InstableTest.java:46)

```

Do you have an idea why this might happens?

**Comment by nniikkoollaaii** [comment]
Hi @Nipahu , 
yes this is a known problem (therefore the test class is named "...InstableTest").

The test is sometimes working (see [here](https://github.com/heutelbeck/sapl-policy-engine/runs/2992733482?check_suite_focus=true#step:6:1301) and sometimes it isn't.

I'm unable to trigger the test to fail on my workstation to debug it further so I enabled the test case at the weekend. And after the Github Actions Matrix build executed the test multiple times successfully, I left the test enabled.

@heutelbeck already told me, that the test is failing on his workstation and provided me with the logs as I enabled the TRACE logging on this module.

It was the right step from you to disable this test. Thank you!
