### ISSUE TITLE
Feature Request: Ability to scan directory hierarchy for SAPL files

### ISSUE THREAD

**Issue by rohitranjan1991** [heutelbeck/sapl-policy-engine#39]
The idea here is to add the ability in the engine in case of FILESYSTEM SAPL file scanning so that it can also look for SAPL files inside the directories. This will be very useful for big projects where we need to maintain a lot of SAPL files. This feature will help developers segregate policies with folders.

**Comment by heutelbeck** [comment]
I just added this enhancement to the embedded PDP/Server LT. This feature has not been a high priority so far. But as I needed to clean up that code anyway, I implemented this feature.

Thanks for the suggestion. I think this is helpful.

Please remember that when updating the policies on the file system, you have to be careful with renaming to not trigger bad "in-between" decisions, as renaming is not atomic.
